<?php

namespace CG\Tests;


use CG\MarsRover;
use PHPUnit\Framework\TestCase;

class MarsRoverTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testRunsMissionSingleRover()
    {
        $data = "5 5\n".
            "1 2 N\n" .
            "LMLMLMLMM";

        $endData = [["X" => 1, "Y" => 3, "direction" => "N"]];

        $mission = new MarsRover($data);

        $endPositions = $mission->runMission();

        self::assertEquals($endData, $endPositions);
    }

    public function testRunsMissionMultipleRovers()
    {
        $data = "5 5\n".
            "1 2 N\n" .
            "LMLMLMLMM\n" .
            "3 3 E\n" .
            "MMRMMRMRRM";

        $endData = [
            ["X" => 1, "Y" => 3, "direction" => "N"],
            ["X" => 5, "Y" => 1, "direction" => "E"]
        ];

        $mission = new MarsRover($data);

        $endPositions = $mission->runMission();

        self::assertEquals($endData, $endPositions);
    }

    public function testOutOfBoundsNorth()
    {
        $data = "5 5\n".
            "1 2 N\n" .
            "MMMMMMMM";

        $endData = [
            ["X" => 1, "Y" => 3, "direction" => "N"],
            ["X" => 5, "Y" => 1, "direction" => "E"]];

        $mission = new MarsRover($data);

        self::expectException('Exception');

        $mission->runMission();
    }

    public function testOutOfBoundsSouth()
    {
        $data = "5 5\n".
            "1 2 S\n" .
            "MMMMMMMM";

        $mission = new MarsRover($data);

        self::expectException('Exception');

        $mission->runMission();
    }

    public function testOutOfBoundsEast()
    {
        $data = "5 5\n".
            "1 2 E\n" .
            "MMMMMMMM";

        $mission = new MarsRover($data);

        self::expectException('Exception');

        $mission->runMission();
    }

    public function testOutOfBoundsWest()
    {
        $data = "5 5\n".
            "1 2 W\n" .
            "MMMMMMMM";

        $mission = new MarsRover($data);

        self::expectException('Exception');

        $mission->runMission();
    }

}
